### ISSUE TITLE
Running your fork of kevaldoshi17/NVIDIA_AICITY produced empty result

### ISSUE THREAD

**Issue by hieplpvip** [Mandroide/gpasb-nvidia2021-track4#1]
Hi,

I'm having some problems running your fork of kevaldoshi17/NVIDIA_AICITY. I know this is not the right repo, but I can't create issues for a fork, and this repo is of the same topic, so I think it's appropriate to create an issue here.

I'm running your code with the 2019 track 3 testset (not sure if it's a problem, but as far as I know the datasets don't change between years). I only made some minor changes to `extract_frames.py` to not load `DOT Iowa Accident Labels`. You can find my working notebook here: https://github.com/hieplpvip/traffic-anomaly-detection-baseline/blob/master/notebook.ipynb. I got an empty `result.csv`. The `*.npy` files are also very small:

```
4.0K    bounds1.npy
4.0K    bounds2.npy
12K     centers1.npy
4.0K    centers2.npy
80K     change.npy
4.0K    result1.npy
4.0K    result2.npy
```

I don't really know what to do now (been stuck for a few days). Could you take a look at my notebook? Thanks a lot!

**Comment by Mandroide** [comment]
> Hi,
> 
> I'm having some problems running your fork of kevaldoshi17/NVIDIA_AICITY. I know this is not the right repo, but I can't create issues for a fork, and this repo is of the same topic, so I think it's appropriate to create an issue here.
> 
> I'm running your code with the 2019 track 3 testset (not sure if it's a problem, but as far as I know the datasets don't change between years). I only made some minor changes to `extract_frames.py` to not load `DOT Iowa Accident Labels`. You can find my working notebook here: https://github.com/hieplpvip/traffic-anomaly-detection-baseline/blob/master/notebook.ipynb. I got an empty `result.csv`. The `*.npy` files are also very small:
> 
> ```
> 4.0K    bounds1.npy
> 4.0K    bounds2.npy
> 12K     centers1.npy
> 4.0K    centers2.npy
> 80K     change.npy
> 4.0K    result1.npy
> 4.0K    result2.npy
> ```
> 
> I don't really know what to do now (been stuck for a few days). Could you take a look at my notebook? Thanks a lot!

To avoid using the version with spreadsheet, just checkout the commit before "Add ground truth anomaly".

I have tried out the code before, and is not able to detect anomalies. I don't know if there is a modification that went wrong in the fork or the author's algorithm does not work correctly. The [Result.csv](https://github.com/Mandroide/NVIDIA_AICITY/blob/dev/Result.csv) was just a copy & paste from Result.txt the author did.

**Comment by hieplpvip** [comment]
Thanks! I'll try running the original repo to see if it's working.

Btw, I see you pinned your fork of selab-hcmus/AI_City_2020. Does that mean you have managed to get it working?

**Comment by Mandroide** [comment]
> Thanks! I'll try running the original repo to see if it's working.
> 
> Btw, I see you pinned your fork of selab-hcmus/AI_City_2020. Does that mean you have managed to get it working?

I haven't gotten the first functional anomaly detector yet. Most of them are hardcoded, missing stuff or just don't work.

I have mentioned something like that in [Suggestions for upcoming code](https://github.com/Endeavour10020/AiCity-2021-Track4/issues/1#issue-927197795).
